// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bids.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createBid = `-- name: CreateBid :one
INSERT INTO bids (bidder_id, product_id, bid_amount)
VALUES ($1, $2, $3)
RETURNING id, product_id, bidder_id, create_at, bid_amount
`

type CreateBidParams struct {
	BidderID  uuid.UUID `json:"bidder_id"`
	ProductID uuid.UUID `json:"product_id"`
	BidAmount float64   `json:"bid_amount"`
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error) {
	row := q.db.QueryRow(ctx, createBid, arg.BidderID, arg.ProductID, arg.BidAmount)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BidderID,
		&i.CreateAt,
		&i.BidAmount,
	)
	return i, err
}

const getBidsByProductID = `-- name: GetBidsByProductID :many
SELECT id, product_id, bidder_id, create_at, bid_amount FROM bids
WHERE product_id = $1
ORDER BY bid_amount DESC
`

func (q *Queries) GetBidsByProductID(ctx context.Context, productID uuid.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getBidsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BidderID,
			&i.CreateAt,
			&i.BidAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighestBidByProductID = `-- name: GetHighestBidByProductID :one
SELECT id, product_id, bidder_id, create_at, bid_amount FROM bids
WHERE product_id = $1
ORDER BY bid_amount DESC
LIMIT 1
`

func (q *Queries) GetHighestBidByProductID(ctx context.Context, productID uuid.UUID) (Bid, error) {
	row := q.db.QueryRow(ctx, getHighestBidByProductID, productID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BidderID,
		&i.CreateAt,
		&i.BidAmount,
	)
	return i, err
}
